<?php

/**
 * Decks iniciais escolhidos após tutorial/onboarding (20 cartas, singleton).
 */
return [
    'agressivo' => [
        'nome' => 'Assalto Ka\'runa',
        'arquetipo' => 'Agressivo',
        'descricao' => 'Pressão constante com criaturas de Ka\'runa e suporte mecânico.',
        'cartas_chave' => ['berserker-das-brasas', 'drakhar-sombrio', 'lanca-chamas-infernal'],
        'slugs' => [
            'cinzeiro-rastejante',
            'salamandra-de-chamas',
            'berserker-das-brasas',
            'cultista-do-nexus',
            'lanca-chamas-infernal',
            'guardiao-de-lava',
            'feiticeira-do-vulcao',
            'espectro-igneo',
            'colosso-da-escoria',
            'drakhar-sombrio',
            'sacerdotisa-da-chama',
            'comandante-vulcanico',
            'parafuso-ambulante',
            'bomba-andante',
            'atirador-enferrujado',
            'canhao-portatil',
            'vigia-mecanico',
            'tecnico-de-campo',
            'mantis-cacador',
            'besouro-espinhoso',
        ],
    ],
    'controle' => [
        'nome' => 'Domínio Ybyrá',
        'arquetipo' => 'Controle',
        'descricao' => 'Veneno, cura e debuffs para desgastar o oponente.',
        'cartas_chave' => ['fungo-devorador', 'cobra-rainha', 'anciao-da-floresta'],
        'slugs' => [
            'besouro-espinhoso',
            'vibora-da-raiz',
            'fungo-devorador',
            'druida-da-raiz',
            'pantera-sombria',
            'lagarto-de-cristal',
            'xama-do-pantano',
            'mantis-cacador',
            'urso-ancestral',
            'cobra-rainha',
            'anciao-da-floresta',
            'predador-do-dossel',
            'gorila-de-cipos',
            'espectro-sussurrante',
            'lacaio-podre',
            'banshee-lamentosa',
            'necromante-aprendiz',
            'sombra-vinculada',
            'espectro-guardiao',
            'golem-de-aco',
        ],
    ],
    'equilibrado' => [
        'nome' => 'Legião Mista',
        'arquetipo' => 'Equilibrado',
        'descricao' => 'Curva equilibrada com amostra de cada linhagem.',
        'cartas_chave' => ['comandante-vulcanico', 'pantera-sombria', 'engenheiro-chefe'],
        'slugs' => [
            'cultista-do-nexus',
            'guardiao-de-lava',
            'drakhar-sombrio',
            'comandante-vulcanico',
            'besouro-espinhoso',
            'fungo-devorador',
            'pantera-sombria',
            'druida-da-raiz',
            'bomba-andante',
            'escudo-automato',
            'tecnico-de-campo',
            'golem-de-aco',
            'engenheiro-chefe',
            'espectro-sussurrante',
            'zumbi-colossus',
            'ceifador-das-almas',
            'salamandra-de-chamas',
            'mantis-cacador',
            'atirador-enferrujado',
            'vigia-mecanico',
        ],
    ],
];
